const programmingWords = [
    // --- Easy Difficulty ---
    { english: "Apple", chinese: "苹果", pronunciation: "/ˈæpl/", category: "食物", difficulty: "easy" },
    { english: "Book", chinese: "书", pronunciation: "/bʊk/", category: "物品", difficulty: "easy" },
    { english: "Car", chinese: "汽车", pronunciation: "/kɑːr/", category: "交通", difficulty: "easy" },
    { english: "Dog", chinese: "狗", pronunciation: "/dɒɡ/", category: "动物", difficulty: "easy" },
    { english: "Eat", chinese: "吃", pronunciation: "/iːt/", category: "动作", difficulty: "easy" },
    { english: "Go", chinese: "去", pronunciation: "/ɡəʊ/", category: "动作", difficulty: "easy" },
    { english: "Happy", chinese: "快乐的", pronunciation: "/ˈhæpi/", category: "情感", difficulty: "easy" },
    { english: "Red", chinese: "红色的", pronunciation: "/red/", category: "颜色", difficulty: "easy" },
    { english: "Big", chinese: "大的", pronunciation: "/bɪɡ/", category: "描述", difficulty: "easy" },
    { english: "Water", chinese: "水", pronunciation: "/ˈwɔːtə(r)/", category: "自然", difficulty: "easy" },
    { english: "Friend", chinese: "朋友", pronunciation: "/frend/", category: "人物", difficulty: "easy" },
    { english: "School", chinese: "学校", pronunciation: "/skuːl/", category: "地点", difficulty: "easy" },
    { english: "Home", chinese: "家", pronunciation: "/həʊm/", category: "地点", difficulty: "easy" },
    { english: "Play", chinese: "玩", pronunciation: "/pleɪ/", category: "动作", difficulty: "easy" },
    { english: "Variable", chinese: "变量", pronunciation: "/ˈveəriəbl/", category: "编程", difficulty: "easy" },
    { english: "Function", chinese: "函数", pronunciation: "/ˈfʌŋkʃn/", category: "编程", difficulty: "easy" },
    { english: "Loop", chinese: "循环", pronunciation: "/luːp/", category: "编程", difficulty: "easy" },
    { english: "Array", chinese: "数组", pronunciation: "/əˈreɪ/", category: "编程", difficulty: "easy" },
    { english: "Code", chinese: "代码", pronunciation: "/kəʊd/", category: "编程", difficulty: "easy" },
    { english: "If", chinese: "如果", pronunciation: "/ɪf/", category: "编程", difficulty: "easy" },

    // --- Medium Difficulty ---
    { english: "Beautiful", chinese: "美丽的", pronunciation: "/ˈbjuːtɪfl/", category: "描述", difficulty: "medium" },
    { english: "Interesting", chinese: "有趣的", pronunciation: "/ˈɪntrəstɪŋ/", category: "描述", difficulty: "medium" },
    { english: "Difficult", chinese: "困难的", pronunciation: "/ˈdɪfɪkəlt/", category: "描述", difficulty: "medium" },
    { english: "Knowledge", chinese: "知识", pronunciation: "/ˈnɒlɪdʒ/", category: "概念", difficulty: "medium" },
    { english: "Experience", chinese: "经验", pronunciation: "/ɪkˈspɪəriəns/", category: "概念", difficulty: "medium" },
    { english: "Company", chinese: "公司", pronunciation: "/ˈkʌmpəni/", category: "组织", difficulty: "medium" },
    { english: "Government", chinese: "政府", pronunciation: "/ˈɡʌvənmənt/", category: "组织", difficulty: "medium" },
    { english: "Problem", chinese: "问题", pronunciation: "/ˈprɒbləm/", category: "概念", difficulty: "medium" },
    { english: "Language", chinese: "语言", pronunciation: "/ˈlæŋɡwɪdʒ/", category: "概念", difficulty: "medium" },
    { english: "Important", chinese: "重要的", pronunciation: "/ɪmˈpɔːtnt/", category: "描述", difficulty: "medium" },
    { english: "Object", chinese: "对象", pronunciation: "/ˈɒbdʒɪkt/", category: "编程", difficulty: "medium" },
    { english: "Method", chinese: "方法", pronunciation: "/ˈmeθəd/", category: "编程", difficulty: "medium" },
    { english: "Event", chinese: "事件", pronunciation: "/ɪˈvent/", category: "编程", difficulty: "medium" },
    { english: "Parameter", chinese: "参数", pronunciation: "/pəˈræmɪtə/", category: "编程", difficulty: "medium" },
    { english: "Class", chinese: "类", pronunciation: "/klɑːs/", category: "编程", difficulty: "medium" },

    // --- Hard Difficulty ---
    { english: "Consequence", chinese: "后果，结果", pronunciation: "/ˈkɒnsɪkwəns/", category: "概念", difficulty: "hard" },
    { english: "Ubiquitous", chinese: "无处不在的", pronunciation: "/juːˈbɪkwɪtəs/", category: "描述", difficulty: "hard" },
    { english: "Plethora", chinese: "过多，过量", pronunciation: "/ˈpleθərə/", category: "数量", difficulty: "hard" },
    { english: "Exacerbate", chinese: "使恶化", pronunciation: "/ɪɡˈzæsəbeɪt/", category: "动作", difficulty: "hard" },
    { english: "Conscientious", chinese: "认真的", pronunciation: "/ˌkɒnʃiˈenʃəs/", category: "描述", difficulty: "hard" },
    { english: "Superfluous", chinese: "多余的", pronunciation: "/suːˈpɜːfluəs/", category: "描述", difficulty: "hard" },
    { english: "Dichotomy", chinese: "一分为二", pronunciation: "/daɪˈkɒtəmi/", category: "概念", difficulty: "hard" },
    { english: "Epistemology", chinese: "认识论", pronunciation: "/ɪˌpɪstəˈmɒlədʒi/", category: "哲学", difficulty: "hard" },
    { english: "Quintessential", chinese: "精髓的", pronunciation: "/ˌkwɪntɪˈsenʃl/", category: "描述", difficulty: "hard" },
    { english: "Algorithm", chinese: "算法", pronunciation: "/ˈælɡərɪðəm/", category: "编程", difficulty: "hard" },
    { english: "Asynchronous", chinese: "异步", pronunciation: "/eɪˈsɪŋkrənəs/", category: "编程", difficulty: "hard" },
    { english: "Compiler", chinese: "编译器", pronunciation: "/kəmˈpaɪlə/", category: "编程", difficulty: "hard" },
    { english: "Recursion", chinese: "递归", pronunciation: "/rɪˈkɜːʃn/", category: "编程", difficulty: "hard" },
    { english: "Syntax", chinese: "语法", pronunciation: "/ˈsɪntæks/", category: "编程", difficulty: "hard" },
    { english: "Debugging", chinese: "调试", pronunciation: "/ˌdiːˈbʌɡɪŋ/", category: "编程", difficulty: "hard" }
]; 